### ISSUE TITLE
按照教程按照一直报错

### ISSUE THREAD

**Issue by lsw1990** [beautywe/framework#9]
D:\software-development\mini-program\my-app>beautywe run dev
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn D:\software-development\mini-program\my-app\node_modules\.bin\gulp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by JerryC8080** [comment]
请问你的 Node.js 版本是多少
